---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
server:
  port: 8020   # Select any available port if neither port nor server port are specified.


# Items that apply to ALL profiles:
spring:
 kafka:
  bootstrap-servers: localhost:9092
  producer:
   keySerializer: org.apache.kafka.common.serialization.StringSerializer
   valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumer:
   group-id: group_id
   key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
   value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer2
   properties:
    spring.json.trusted.packages: com.lguplus.model
    spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
    spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

 ## MariaDB
  #datasource:
    #url: jdbc:mariadb://localhost:3306/testdb
    #username: root
    #password: ehrud1234
    #driver-class-name: org.mariadb.jdbc.Driver
    
 datasource:
  url: jdbc:postgresql://localhost:5432/testdb
  username: postgres
  password: 1234
  
  #Connection Pool
  hikari:
   connection-timeout: 20000
   maximum-pool-size: 10
 
 jpa:
  database: POSTGRESQL
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  show-sql: false
  generate-ddl: false
  hibernate:
   ddl-auto: none
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
  properties:
   hibernate:
    temp:
     use_jdbc_metadata_defaults: false
feign:
  client:
    config:
      default:    # or feign name
        connectTimeout: 5000  
        readTimeout: 5000
