---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
      
server:
  port: 8020   # Select any available port if neither port nor server port are specified.


# Items that apply to ALL profiles:
spring:

 ## MariaDB
  #datasource:
    #url: jdbc:mariadb://localhost:3306/testdb
    #username: root
    #password: ehrud1234
    #driver-class-name: org.mariadb.jdbc.Driver
    
 datasource:
  url: jdbc:postgresql://localhost:5432/testdb
  username: postgres
  password: 1234
  
  #Connection Pool
  hikari:
   connection-timeout: 20000
   maximum-pool-size: 10
 
 jpa:
  database: POSTGRESQL
  database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  show-sql: false
  generate-ddl: false
  hibernate:
   ddl-auto: none
   naming:
    physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
  properties:
   hibernate:
    temp:
     use_jdbc_metadata_defaults: false
     
feign:
  client:
    config:
      default:    # or feign name
        connectTimeout: 5000  
        readTimeout: 5000

 kafka:
  producer:
   bootstrap-servers: localhost:9092
   key-serializer: org.apache.kafka.common.serialization.StringSerializer.class
   value-serializer: org.springframework.kafka.support.serializer.JsonSerializer.class
  consumer:
   bootstrap-servers: localhost:9092
   group-id: "group_id"
   key-deserializer: org.apache.kafka.common.serialization.StringDeserializer.class
   value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer.class
   properties:
    spring:
     json:
      trusted:
       packages: com.lguplus.model
